### ISSUE TITLE
Error when using Consistency::fullConsistent()

### ISSUE THREAD

**Issue by Sheridan963** [alsbury/chiphpotle-rest#1]
Hello,

I've this error when I use Consistency::fullConsistent():
"proto: (line 1:41): error parsing "fullyConsistent", oneof authzed.api.v1.Consistency.requirement is already set"

`$request = (new ReadRelationshipsRequest())
            ->setConsistency(Consistency::fullConsistent())
            ->setRelationshipFilter($filter);`

**Comment by alsbury** [comment]
Hello @Sheridan963,
Thanks for the bug report. I fixed the issue and pushed version v0.1.10.

Also note that `fullConsistent` is a typo and I fixed it by renaming it to `fullyConsistent`.

I'm going to close the issue assuming it is fixed.
