### ISSUE TITLE
Symfony 7 support

### ISSUE THREAD

**Issue by ldebrouwer** [alsbury/chiphpotle-rest#2]
The current version of the library is incompatible with Symfony 7. Specifically `Chiphpotle\Rest\Normalizer\JaneObjectNormalizer` is incompatible with the Symfony interfaces it attempts to implement.

Further incompatibilities may be abound.

**Comment by ldebrouwer** [comment]
I've dug a bit deeper into this, and it's down to several normalisers being incompatible with the interfaces of `symfony/serializer` version `^7.0`.

**Comment by thewunder** [comment]
Thanks for the report I will take a look later today.

**Comment by thewunder** [comment]
Fixed in v0.7.1
